-- SCRIPT SQL PARA SUPABASE --
-- Copie e cole no painel SQL Editor do Supabase

-- Tabela de Autores
CREATE TABLE autores (
  id TEXT PRIMARY KEY, 
  nome TEXT NOT NULL,
  nome_completo TEXT
);

-- Tabela de Artigos
CREATE TABLE artigos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo TEXT NOT NULL,
  ano INTEGER,
  source_titulo TEXT,
  qt_citacao INTEGER DEFAULT 0,
  doi TEXT,
  link TEXT,
  resumo TEXT
);

-- Tabela de Palavras-chaves
CREATE TABLE palavras_chaves (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  palavra_chave TEXT NOT NULL UNIQUE
);

-- Tabela de Referências
CREATE TABLE referencias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conteudo_referencia TEXT
);

-- Relacionamento: Artigo <-> Autor
CREATE TABLE artigo_autor (
  id_artigo BIGINT REFERENCES artigos(id) ON DELETE CASCADE,
  id_autor TEXT REFERENCES autores(id) ON DELETE CASCADE,
  PRIMARY KEY (id_artigo, id_autor)
);

-- Relacionamento: Artigo <-> Palavra-chave
CREATE TABLE artigo_palavra_chave (
  id_artigo BIGINT REFERENCES artigos(id) ON DELETE CASCADE,
  id_palavra_chave BIGINT REFERENCES palavras_chaves(id) ON DELETE CASCADE,
  PRIMARY KEY (id_artigo, id_palavra_chave)
);

-- Relacionamento: Artigo <-> Referência
CREATE TABLE artigo_referencia (
  id_artigo BIGINT REFERENCES artigos(id) ON DELETE CASCADE,
  id_referencia BIGINT REFERENCES referencias(id) ON DELETE CASCADE,
  PRIMARY KEY (id_artigo, id_referencia)
);
